name: tiny_queue
version: 0.1.0
author: Richard Lincoln <r.w.lincoln@gmail.com>
description: Simple FIFO queue implementation
homepage: https://github.com/rwl/tiny_queue.dart
environment:
  sdk: '>=1.0.0'
dev_dependencies:
  test: "^0.12.6"
